# Build Julia binary for arm32-bit armv7-a devices e.g. RaspberryPi 2 or 3

FROM balenalib/raspberrypi3:bookworm-20240930

# install dependencies
RUN apt-get update && \
    apt-get install -y build-essential libatomic1 python3 gfortran perl wget m4 cmake pkg-config zlib1g-dev \
    git \
    unzip \
    && \
    apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

# build julia from source
ARG JL_VERSION="terasaki/v1.11.1-arm-patch-2"
ARG WDIR=/home/pi/work
ARG JL_BUILD_DIR=$WDIR/build
WORKDIR $WDIR
RUN echo "\
prefix=/home/pi/julia-$JL_VERSION\n\
USE_BINARYBUILDER=1\n\
CFLAGS += "-mfpu=neon-vfpv4"\n\
CFLAGS += "-mfloat-abi=hard"\n\
CXXFLAGS += "-mfpu=neon-vfpv4"\n\
CXXFLAGS += "-mfloat-abi=hard"\n\
" > Make.user && \
    cat Make.user && \
    git clone --depth=1 -b $JL_VERSION https://github.com/terasakisatoshi/julia.git $JL_BUILD_DIR && \
    cp Make.user $JL_BUILD_DIR && \
    cd $JL_BUILD_DIR && make -j
